### ISSUE TITLE
[FAQ question] For the main README: "How does it compare to a pure ruby implementation?"

### ISSUE THREAD

**Issue by rubyFeedback** [kojix2/sdust.cr#1]
Hey there kojix2,

If you ever have some time, could you give an estimate how much faster the crystal implementation
is, compared to a pure ruby implementation? This does not necessarily have to be 100% exact,
just a rough comparison, and mentioning this in the FAQ, if you have the time and motivation.

Thanks for reading this issue request.

**Comment by kojix2** [comment]
Thank you for your comment.

The original Sdust makes extensive use of bitwise operations, and sdust.cr is the same implementation. This means that sdust.cr is not written in an object-oriented manner. So it is difficult to simply replace it with Ruby.

When implementing sdust in Ruby, there are several possible patterns.

      (1) Completely Ruby style implementation.
      (2) Use bitwise operations instead of object-oriented.
      (3) Use the original sdust with C extensions or FFI.

Obviously, the most practical is (3). It is as fast as the C language.
(2) is useful for comparing Ruby and Crystal. (1) is useful for measuring the speed of Ruby when written in a normal way.

In any case, I will not rewrite to Ruby. I don't do benchmarking either. If you are interested, give it a try. I think it will take some time and effort.
